### ISSUE TITLE
Add a test suite!

### ISSUE THREAD

**Issue by ifigueroap** [ifigueroap/racket-quickcheck#10]
duh, we need some tests, don't we?

**Comment by dented42** [comment]
Haha, I was thinking the same thing.

Why don't we make some empty test files and a simple harness to start? Otherwise we might have multiple people each starting from scratch which will make merging a pain.

I can get a pull request ready fairly quickly.

**Comment by dented42** [comment]
Although, now that I think about it, should we stick them in a separate package? If we move everything into a 'quickcheck' subdirectory, and have put a 'quickcheck-tests' directory along side it. You'd have to change the package specification to point to the subdirectory, but then we'd have the advantage of users not having to download the tests (and depend on a test framework) but still having them in the same repository.

**Comment by jackfirth** [comment]
Depending on the tests and your testing style, you may be better off with [test submodules](http://docs.racket-lang.org/guide/Module_Syntax.html#%28part._main-and-test%29). They make it very easy to embed the tests directly into the code you're testing without requiring dependencies on testing libraries at runtime. This works best for unit tests, more intensive testing like load testing is usually better off in separate files or packages.

**Comment by jackfirth** [comment]
Closed by #25, though it's a primitive test suite at the moment.
