### ISSUE TITLE
Avoid `check` conflict with RackUnit

### ISSUE THREAD

**Issue by ifigueroap** [ifigueroap/racket-quickcheck#11]
I think it is necessary to avoid conflicts with RackUnit, namely the export of the `check` symbol. In the end, the only difference between `check` and `quickcheck` is the `config` argument. Therefore we could have a naming convention like:

`quickcheck` : the default `quick` config
`quickcheck/config`: the check that takes an explicit config.

Then in the yet-to-be-implemented quickcheck-rackunit integration package we can define `check-property` and `check-property/config` as suggested by @jackfirth

What do you think?

**Comment by jackfirth** [comment]
This naming works very well, since `a/b` is pronounced "a with b" in scheme naming conventions. Definitely a good idea.
