### ISSUE TITLE
quickcheck-RackUnit integration as standalone package vs multi-collection package

### ISSUE THREAD

**Issue by ifigueroap** [ifigueroap/racket-quickcheck#12]
??

**Comment by jackfirth** [comment]
Multicollection package would work really well here. Make a "rackunit" folder with a "quickcheck.rkt" module that does the necessary renaming/fudging/what-have-you to avoid conflicts and provides the rackunit checks. You can see an example of how to implement this in my [lens](https://github.com/jackfirth/lens) package, though just replace "unstable" with "rackunit".
