### ISSUE TITLE
Examples on how to create new generators

### ISSUE THREAD

**Issue by pmatos** [ifigueroap/racket-quickcheck#31]
It would be great to clarify with a few examples how to create new generators. I can see the `make-generator` function from the docs but it's not totally clear how to then call the other generators to fill in the gaps. For example, imagine I have a structure for a 2d-point, which has two integers. How can I create a generator for the structure reusing the generators for integers?

Can we add an example like this to the docs? If you explain it to me, I will create a pull request to add it to the docs.

**Comment by default-kramer** [comment]
I've just struggled with the same problem for a while, and I came up with this `with-generators` macro. I'd be happy to make a PR to add `with-generators` and documentation if this looks OK:

```
#lang racket
(require quickcheck)
(require (for-syntax syntax/parse))

(define-syntax (with-generators stx)
  (syntax-parse stx
    [(_ ([id:id gen]
         [id-rest:id gen-rest] ...)
        body ...+)
     #:declare gen (expr/c #'generator?)
     #'(let ([id gen.c])
         (generator-bind
          id
          (λ(id)
            (with-generators ([id-rest gen-rest] ...)
              body ...))))]
    [(_ () body ...+)
     #'(let ([proc (λ(i rgen) body ...)])
         (generator proc))]))

(define (choose-bool)
  (choose-mixed (list (generator-unit #t)
                      (generator-unit #f))))

(struct foo (a b) #:transparent)

(define (choose-foo [recurse-limit 2])
  (with-generators ([a-val (choose-integer 0 10)]
                    [recurse? (choose-bool)]
                    [b-val (if (and recurse?
                                    (recurse-limit . > . 0))
                               (choose-foo (sub1 recurse-limit))
                               (choose-string choose-printable-ascii-char 6))])
    (foo a-val b-val)))

(quickcheck (property ([x (choose-foo)])
                      (println x)
                      #t))
```

**Comment by ifigueroap** [comment]
Thanks for your contribution, could you please send a pull request so I can accept it?
