### ISSUE TITLE
Fix build dependencies

### ISSUE THREAD

**Issue by dented42** [ifigueroap/racket-quickcheck#4]
Building the documentation requires scribble-lib, the info.rkt file should be updated to reflect this.

**Comment by ifigueroap** [comment]
I just made a commit with updated deps, it should be ok, can you please confirm to then close this ticket? Thanks!

**Comment by dented42** [comment]
It looks like you're defining deps twice, also it's my understanding that dependencies like scribble-lib that are only required to build the package should be listed in build-deps. I submitted a pull request that should do the trick.
