### ISSUE TITLE
generator-unit is not defined error

### ISSUE THREAD

**Issue by maueroats** [ifigueroap/racket-quickcheck#49]
The following program does not successfully compile when loaded as a single document in Racket. When typed in two lines at the command line it does work.
Addressed in PR #48.
```scheme
#lang racket
(require quickcheck)
(define (choose-n)
  (bind-generators
   ([n (choose-integer -10 10)])
   n))
```

**Comment by ifigueroap** [comment]
I'm sorry, it's been a while since I'm not actively maintaining this repository. I understand the PR and will merge it, though. Thanks for the contribution. 

PR merged.
