### ISSUE TITLE
RackUnit integration?

### ISSUE THREAD

**Issue by jackfirth** [ifigueroap/racket-quickcheck#9]
I'd really like to use this, but when properties fail there's no exceptions thrown, only printed output. This makes running property tests in an automated testing environment not possible without additional work. I'd ideally like something that works with RackUnit, so I could write stuff like this:

```
(check-property some-property)
(check-property/config config some-property)
```

And have failures look like RackUnit failures:

```
--------------------
FAILURE
property:         some-property
falsifiable-case: some-case-for-which-property-is-false
stamps:           '(label ...)
total-cases:      100
case-size:        10
location:         (unsaved-editor 6 0 36 18)
expression:       (check-property some-property)

<exn> Check failure
--------------------
```

Or something along those lines.

**Comment by ifigueroap** [comment]
I see your point and I think it makes lots of sense. I wonder whether it is better to add a dependency to rackunit directly, or to have an extra package racket-quickcheck-rackunit that provides the integration. I don't know if I can specify optional dependencies for the package :/

**Comment by jackfirth** [comment]
An extra package would work fine I think

**Comment by ifigueroap** [comment]
I got a prototype that outputs errors like this:

```
--------------------
FAILURE
ntest:      0
stamps:     ()
arguments:  "str = \"\\u0002\\u0003\\u0002\""
property:   #<property>
name:       quickcheck/e
location:   (#<path:/Users/ismael/Desktop/quickcheck-rackunit.rkt> 11 0 205 44)
expression: (quickcheck/e string->number-returns-number)
params:     (#<property>)

. . Falsifiable
--------------------
```

I think that should be enough for now

**Comment by ifigueroap** [comment]
Commit 1ace5e3f7a8bcb00ad1f473435a156545a4413af includes two new forms: `check/e` and `quickcheck/e`. They are just like `check` and `quickcheck` but produce RackUnit exceptions when the property is falsifiable (i.e exceptions of type `exn:fail:check`)

Please report back if it works for you, to then close this issue.

Thanks

**Comment by dented42** [comment]
Might as well ads my 2p, I'd probably stick it in a separate package, that way you can export a more rackunit friendly 'check-property' that would be out of place among the rest of quickcheck's naming scheme.

**Comment by jackfirth** [comment]
Agree with @dented42 on that, especially because `quickcheck` and `rackunit` already collide as is (both provide `check`). I can deal with both of those problems with `except-in` and `rename-in` for now. Thank you very much for the quick addition though.
